// <auto-generated />
using System;
using AssetManagement.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssetManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326060822_AddSeedEmployees")]
    partial class AddSeedEmployees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssetManagement.API.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("AssetTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("BrandName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CourierTrackingAttachment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("PurchaseCost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("WarrantyExpiry")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("AssignedEmployeeId");

                    b.HasIndex("BranchId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("AssetManagement.API.Models.AssetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("AssetCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8a88ae2-f263-45cf-8086-91ff3a270431"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 392, DateTimeKind.Unspecified).AddTicks(7840), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Laptops, Mobiles, etc.",
                            IsActive = true,
                            Name = "Electronic Gadgets"
                        },
                        new
                        {
                            Id = new Guid("01c7667e-c8c3-4437-9251-7f72cadd5593"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 392, DateTimeKind.Unspecified).AddTicks(8117), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tables, Chairs, etc.",
                            IsActive = true,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = new Guid("7807dfa2-4e33-4c82-8736-815f5a4d8f11"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 392, DateTimeKind.Unspecified).AddTicks(8119), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Keyboards, Mice, etc.",
                            IsActive = true,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("AssetManagement.API.Models.AssetHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FromEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewCondition")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OldCondition")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("PerformedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<Guid?>("ToEmployeeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("FromEmployeeId");

                    b.HasIndex("PerformedById");

                    b.HasIndex("ToEmployeeId");

                    b.ToTable("AssetHistories");
                });

            modelBuilder.Entity("AssetManagement.API.Models.AssetIdConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("LastSequence")
                        .HasColumnType("integer");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("AssetIdConfigs");
                });

            modelBuilder.Entity("AssetManagement.API.Models.AssetRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AdminApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApprovedByHrId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedAssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("HrApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReplacementAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByAdminId");

                    b.HasIndex("ApprovedByHrId");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("AssignedAssetId");

                    b.HasIndex("ReplacementAssetId");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.HasIndex("RequestedById");

                    b.ToTable("AssetRequests");
                });

            modelBuilder.Entity("AssetManagement.API.Models.AssetSpecValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpecDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpecDefinitionId");

                    b.HasIndex("AssetId", "SpecDefinitionId")
                        .IsUnique();

                    b.ToTable("AssetSpecValues");
                });

            modelBuilder.Entity("AssetManagement.API.Models.AssetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("AssetTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5cb47334-4c76-4601-a08c-46e312ed59a7"),
                            CategoryId = new Guid("e8a88ae2-f263-45cf-8086-91ff3a270431"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 393, DateTimeKind.Unspecified).AddTicks(1613), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = new Guid("5e3c0b99-efda-4d23-a60c-6868d78794d2"),
                            CategoryId = new Guid("e8a88ae2-f263-45cf-8086-91ff3a270431"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 393, DateTimeKind.Unspecified).AddTicks(1878), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Chargers"
                        },
                        new
                        {
                            Id = new Guid("3c16c20c-3dd8-428e-b3c3-46d65d0464b9"),
                            CategoryId = new Guid("7807dfa2-4e33-4c82-8736-815f5a4d8f11"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 393, DateTimeKind.Unspecified).AddTicks(1880), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Keyboard"
                        },
                        new
                        {
                            Id = new Guid("12f30718-65e0-4426-acb9-b28e980de613"),
                            CategoryId = new Guid("7807dfa2-4e33-4c82-8736-815f5a4d8f11"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 393, DateTimeKind.Unspecified).AddTicks(1991), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Mouse"
                        },
                        new
                        {
                            Id = new Guid("a1684a71-0609-49a6-b637-251de31a32c2"),
                            CategoryId = new Guid("e8a88ae2-f263-45cf-8086-91ff3a270431"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 393, DateTimeKind.Unspecified).AddTicks(1995), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = new Guid("a6b45145-1844-4c52-9188-a6891a34fee2"),
                            CategoryId = new Guid("01c7667e-c8c3-4437-9251-7f72cadd5593"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 393, DateTimeKind.Unspecified).AddTicks(1998), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Table"
                        },
                        new
                        {
                            Id = new Guid("60891474-041a-436c-9e2e-94bb162d454d"),
                            CategoryId = new Guid("01c7667e-c8c3-4437-9251-7f72cadd5593"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 393, DateTimeKind.Unspecified).AddTicks(2024), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Chair"
                        });
                });

            modelBuilder.Entity("AssetManagement.API.Models.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("943dad51-08de-42b3-b184-de1f272743b6"),
                            Address = "Coimbatore, TN",
                            Code = "CBE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 19, 669, DateTimeKind.Unspecified).AddTicks(5449), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Coimbatore"
                        },
                        new
                        {
                            Id = new Guid("f0bd8ca8-d641-40d1-8562-ef748bfa6ec7"),
                            Address = "Perundurai, TN",
                            Code = "PDR",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 19, 669, DateTimeKind.Unspecified).AddTicks(5846), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Perundurai"
                        });
                });

            modelBuilder.Entity("AssetManagement.API.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AssetManagement.API.Models.SpecDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("SpecDataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SpecName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId", "SpecName")
                        .IsUnique();

                    b.ToTable("SpecDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("555d1ab0-cfb4-424a-bc9e-4660d8af8c78"),
                            AssetTypeId = new Guid("5cb47334-4c76-4601-a08c-46e312ed59a7"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 393, DateTimeKind.Unspecified).AddTicks(4671), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 1,
                            IsRequired = true,
                            SpecDataType = "text",
                            SpecName = "RAM"
                        },
                        new
                        {
                            Id = new Guid("283067c6-7e80-4107-9b42-dab7df858814"),
                            AssetTypeId = new Guid("5cb47334-4c76-4601-a08c-46e312ed59a7"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 393, DateTimeKind.Unspecified).AddTicks(4956), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 2,
                            IsRequired = true,
                            SpecDataType = "text",
                            SpecName = "Processor"
                        },
                        new
                        {
                            Id = new Guid("934bb7e0-7176-4929-8ae6-25b91f415084"),
                            AssetTypeId = new Guid("5cb47334-4c76-4601-a08c-46e312ed59a7"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 393, DateTimeKind.Unspecified).AddTicks(4959), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 3,
                            IsRequired = true,
                            SpecDataType = "text",
                            SpecName = "Storage"
                        },
                        new
                        {
                            Id = new Guid("9a40815c-e5f2-4365-b870-509d514c6c70"),
                            AssetTypeId = new Guid("5cb47334-4c76-4601-a08c-46e312ed59a7"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 393, DateTimeKind.Unspecified).AddTicks(4962), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 4,
                            IsRequired = false,
                            SpecDataType = "text",
                            SpecName = "Screen Size"
                        },
                        new
                        {
                            Id = new Guid("fc2e60b5-a17d-4cff-b5a3-dc8f4fe0e85d"),
                            AssetTypeId = new Guid("5cb47334-4c76-4601-a08c-46e312ed59a7"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 393, DateTimeKind.Unspecified).AddTicks(4967), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 5,
                            IsRequired = true,
                            SpecDataType = "text",
                            SpecName = "OS"
                        });
                });

            modelBuilder.Entity("AssetManagement.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ba9ed1ab-bba9-4bf9-b527-ac21fa42f8c1"),
                            BranchId = new Guid("943dad51-08de-42b3-b184-de1f272743b6"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 19, 998, DateTimeKind.Unspecified).AddTicks(9008), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@assetorg.com",
                            EmployeeId = "EMP-001",
                            FullName = "System Admin",
                            PasswordHash = "$2a$11$nh5j.QP07UHftDVR/aili.bb2L0D9oitwGRJVjMxHn.cHVTo1c.6e",
                            Role = "Admin",
                            Status = "Active",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 19, 998, DateTimeKind.Unspecified).AddTicks(9556), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-b222-222222222222"),
                            BranchId = new Guid("943dad51-08de-42b3-b184-de1f272743b6"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 259, DateTimeKind.Unspecified).AddTicks(120), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "hr@assetorg.com",
                            EmployeeId = "EMP-002",
                            FullName = "HR Manager",
                            PasswordHash = "$2a$11$X8Z7NQ19Ir9sivrcT95v3utVODiwWnh3sLACoKMSO61w34VZYql8u",
                            Role = "HR",
                            Status = "Active",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 259, DateTimeKind.Unspecified).AddTicks(127), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-4333-b333-333333333333"),
                            BranchId = new Guid("f0bd8ca8-d641-40d1-8562-ef748bfa6ec7"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 391, DateTimeKind.Unspecified).AddTicks(4863), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "employee@assetorg.com",
                            EmployeeId = "EMP-003",
                            FullName = "Test Employee",
                            PasswordHash = "$2a$11$2hI5EFn1462Q6qMWerj6vOAknAzeAUeZz4aQk96ZuX2DHIVQETEf6",
                            Role = "Employee",
                            Status = "Active",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 6, 8, 20, 391, DateTimeKind.Unspecified).AddTicks(4866), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AssetManagement.API.Models.Asset", b =>
                {
                    b.HasOne("AssetManagement.API.Models.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetManagement.API.Models.User", "AssignedEmployee")
                        .WithMany()
                        .HasForeignKey("AssignedEmployeeId");

                    b.HasOne("AssetManagement.API.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");

                    b.Navigation("AssignedEmployee");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("AssetManagement.API.Models.AssetHistory", b =>
                {
                    b.HasOne("AssetManagement.API.Models.Asset", "Asset")
                        .WithMany("History")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetManagement.API.Models.User", "FromEmployee")
                        .WithMany()
                        .HasForeignKey("FromEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssetManagement.API.Models.User", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssetManagement.API.Models.User", "ToEmployee")
                        .WithMany()
                        .HasForeignKey("ToEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("FromEmployee");

                    b.Navigation("PerformedBy");

                    b.Navigation("ToEmployee");
                });

            modelBuilder.Entity("AssetManagement.API.Models.AssetRequest", b =>
                {
                    b.HasOne("AssetManagement.API.Models.User", "ApprovedByAdmin")
                        .WithMany()
                        .HasForeignKey("ApprovedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssetManagement.API.Models.User", "ApprovedByHr")
                        .WithMany()
                        .HasForeignKey("ApprovedByHrId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssetManagement.API.Models.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId");

                    b.HasOne("AssetManagement.API.Models.Asset", "AssignedAsset")
                        .WithMany()
                        .HasForeignKey("AssignedAssetId");

                    b.HasOne("AssetManagement.API.Models.Asset", "ReplacementAsset")
                        .WithMany()
                        .HasForeignKey("ReplacementAssetId");

                    b.HasOne("AssetManagement.API.Models.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByAdmin");

                    b.Navigation("ApprovedByHr");

                    b.Navigation("AssetType");

                    b.Navigation("AssignedAsset");

                    b.Navigation("ReplacementAsset");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("AssetManagement.API.Models.AssetSpecValue", b =>
                {
                    b.HasOne("AssetManagement.API.Models.Asset", "Asset")
                        .WithMany("SpecValues")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetManagement.API.Models.SpecDefinition", "SpecDefinition")
                        .WithMany()
                        .HasForeignKey("SpecDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("SpecDefinition");
                });

            modelBuilder.Entity("AssetManagement.API.Models.AssetType", b =>
                {
                    b.HasOne("AssetManagement.API.Models.AssetCategory", "Category")
                        .WithMany("AssetTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AssetManagement.API.Models.Notification", b =>
                {
                    b.HasOne("AssetManagement.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AssetManagement.API.Models.SpecDefinition", b =>
                {
                    b.HasOne("AssetManagement.API.Models.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");
                });

            modelBuilder.Entity("AssetManagement.API.Models.User", b =>
                {
                    b.HasOne("AssetManagement.API.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("AssetManagement.API.Models.Asset", b =>
                {
                    b.Navigation("History");

                    b.Navigation("SpecValues");
                });

            modelBuilder.Entity("AssetManagement.API.Models.AssetCategory", b =>
                {
                    b.Navigation("AssetTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
